name: elos_app
description: App Elos com Firebase Auth e navegação.
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  firebase_auth_web: ^5.8.15


flutter:
  uses-material-design: true
  assets:
    - lib/assets/1.jpg
    - lib/assets/2.jpg
    - lib/assets/3.jpg
