// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnGsHNxg7deeLRuZ7_rO2QTtKHQxuYnEA',
    appId: '1:1013856830454:web:82ea6f3c5f4ed5262fbdd7',
    messagingSenderId: '1013856830454',
    projectId: 'elos-app-1efa4',
    authDomain: 'elos-app-1efa4.firebaseapp.com',
    storageBucket: 'elos-app-1efa4.firebasestorage.app',
    measurementId: 'G-D22WL05BX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtTgIBV5NlHMIaug_oLKYDr9vfG89jc5c',
    appId: '1:1013856830454:android:64d64b1a0b292b6b2fbdd7',
    messagingSenderId: '1013856830454',
    projectId: 'elos-app-1efa4',
    storageBucket: 'elos-app-1efa4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSrOBZbArcoblNBc3LFiNs-e0mV2E-dic',
    appId: '1:1013856830454:ios:894442ecfd4d30512fbdd7',
    messagingSenderId: '1013856830454',
    projectId: 'elos-app-1efa4',
    storageBucket: 'elos-app-1efa4.firebasestorage.app',
    iosBundleId: 'com.example.elosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSrOBZbArcoblNBc3LFiNs-e0mV2E-dic',
    appId: '1:1013856830454:ios:894442ecfd4d30512fbdd7',
    messagingSenderId: '1013856830454',
    projectId: 'elos-app-1efa4',
    storageBucket: 'elos-app-1efa4.firebasestorage.app',
    iosBundleId: 'com.example.elosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnGsHNxg7deeLRuZ7_rO2QTtKHQxuYnEA',
    appId: '1:1013856830454:web:0b18bf19b1e4ac2e2fbdd7',
    messagingSenderId: '1013856830454',
    projectId: 'elos-app-1efa4',
    authDomain: 'elos-app-1efa4.firebaseapp.com',
    storageBucket: 'elos-app-1efa4.firebasestorage.app',
    measurementId: 'G-G8V4SX33ZT',
  );
}
